### DISCUSSION TITLE
AgentCard specification support for custom headers

### DISCUSSION THREAD

**Discussion by snappyguide** [google/adk-python#1676] [Ideas]
https://a2aproject.github.io/A2A/specification/#55-agentcard-object-structure

Provision in the agent card specification to add Custom Headers similar to securityScheme. Eg: Swagger equivalent of "parameters"

```
parameters:
  - name: X-ENV-CONFIG
    in: header
    description: Environment configuration as a JSON string
    required: false
    schema:
      type: string
      example: '{"environment":"prod","region":"us-west","version":"v2"} or xxx'

```

In my application, from client side, i want to send an environment identifier (which my application agent can look for and process it) to the Agent which cannot be hard coded on tool calling as it is not at application/agent level but user request specific . A provision in specification can standardize the interaction?
