### ISSUE TITLE
MCPTimeout error inside linux container

### ISSUE THREAD

**Issue by lsinghkochava** [google/adk-python#1453]
I have a simple refinement loop agent setup (paired with [mongodb-mcp-server](https://github.com/mongodb-js/mongodb-mcp-server)) that runs perfectly through `adk web`, but this results in a MCPTimeout error when run in a linux container which I had setup following documentation over at https://google.github.io/adk-docs/deploy/gke/#code-files

`{"error": "Timed out while waiting for response to ClientRequest. Waited 5.0 seconds."}`

Here's my mcp configuration - 

```python
mcp_toolset = MCPToolset(
    connection_params=StdioConnectionParams(
        timeout=5,
        server_params=StdioServerParameters(
            command="npx",
            args=[
                "-y",
                "mongodb-mcp-server",
                "--connectionString",
                os.getenv("MONGODB_CONNECTION_STRING"),
                "--readOnly"
            ]
        )
    )
)
```

compose config
```yaml

agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGODB_CONNECTION_STRING=<>
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
```

This may very well be an issue with the SDK (https://github.com/modelcontextprotocol/typescript-sdk/issues/576 or similar). I'm looking to start a conversation on it.
